title: JekyllHIDE
email: 
description: making collections out of TEI into HTML in the browser using CETEIcean
github: https://github.com/FSUDRS/jekyllhide.git
baseurl : "" #change to github project name when it goes up on github pages

collections:
  odfn:
    output : true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']