namespace :pilot do
  desc "create JSON for website"
  task :xml_parse do
    require "rubygems"
    require "nokogiri"
    require "json"
    filenames = Dir.glob("collection/*.xml")
    files = {}
    puts files
    filenames.each do |filename|
      @doc = File.open(filename) { |f| Nokogiri::XML(f) }
      _title = @doc.xpath("//tei:title", "tei" => "http://www.tei-c.org/ns/1.0")
      _author = @doc.at_css("author").content
      _pub = @doc.at_css("publisher").content
      _date = @doc.at_css("date").content.gsub("/\s+/", " ")
      _ps = @doc.css("p")
      puts _title[0].content, _author, _pub, _date
      puts "-------------"
    end
  end
end
